#!/usr/bin/env node
// generate-locale.js - Build script to generate locale constants from mapml-extension
const fs = require('fs');
const path = require('path');

function generateLocaleFile() {
  try {
    // Load and process each language's messages.json file
    const enMessagesPath = path.resolve(__dirname, '../node_modules/mapml-extension/src/_locales/en/messages.json');
    const frMessagesPath = path.resolve(__dirname, '../node_modules/mapml-extension/src/_locales/fr/messages.json');

    if (!fs.existsSync(enMessagesPath)) {
      throw new Error(`English messages.json not found at: ${enMessagesPath}`);
    }
    if (!fs.existsSync(frMessagesPath)) {
      throw new Error(`French messages.json not found at: ${frMessagesPath}`);
    }

    const enMessages = JSON.parse(fs.readFileSync(enMessagesPath, 'utf-8'));
    const frMessages = JSON.parse(fs.readFileSync(frMessagesPath, 'utf-8'));

    // Function to transform messages.json content to the desired structure
    const transformMessages = (messages) => {
      return Object.keys(messages).reduce((acc, key) => {
        if (key !== 'extName' && key !== 'extDescription') {
          acc[key] = messages[key].message;
        }
        return acc;
      }, {});
    };

    // Generate locale objects
    const locale = transformMessages(enMessages);
    const localeFr = transformMessages(frMessages);

    // Generate TypeScript file content
    const tsContent = `// Generated file - do not edit manually
// This file is generated by scripts/generate-locale.js from mapml-extension locale files

export const locale = ${JSON.stringify(locale, null, 2)};

export const localeFr = ${JSON.stringify(localeFr, null, 2)};
`;

    // Ensure the directory exists
    const outputDir = path.resolve(__dirname, '../src/utils/mapml');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the generated TypeScript file
    const outputPath = path.resolve(outputDir, 'generated-locale.ts');
    fs.writeFileSync(outputPath, tsContent, 'utf-8');

    console.log(`✅ Generated locale file: ${outputPath}`);
    console.log(`   - English entries: ${Object.keys(locale).length}`);
    console.log(`   - French entries: ${Object.keys(localeFr).length}`);

  } catch (error) {
    console.error('❌ Failed to generate locale file:', error.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  generateLocaleFile();
}

module.exports = { generateLocaleFile };