/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * @default false
         */
        "controls": boolean;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * @default false
         */
        "static"?: boolean;
        /**
          * Promise-based method to wait until all layers are ready Returns a promise that resolves when all child layers are fully initialized
         */
        "whenLayersReady": () => Promise<PromiseSettledResult<void>[]>;
        "whenProjectionDefined": (projection: string) => Promise<unknown>;
        /**
          * Promise-based method to wait until map is ready Returns a promise that resolves when the map is fully initialized
         */
        "whenReady": () => Promise<void>;
        /**
          * @default 0
         */
        "zoom"?: number;
    }
    interface MapA {
        "href"?: string;
        "inplace"?: boolean;
        "target"?: string;
        "type"?: string;
    }
    interface MapCaption {
    }
    interface MapExtent {
        "_label"?: string;
        "_opacity"?: number;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "hidden": boolean;
        /**
          * @default 1
         */
        "opacity"?: number;
        "units": string;
        "whenLinksReady": () => Promise<PromiseSettledResult<any>[]>;
        "whenReady": () => Promise<void>;
    }
    interface MapFeature {
        "max"?: number;
        "min"?: number;
        "whenReady": () => Promise<void>;
        "zoom"?: number;
    }
    interface MapFeaturecaption {
    }
    interface MapGeometry {
        "cs"?: string;
    }
    interface MapInput {
        "axis"?: string;
        "max"?: string;
        "min"?: string;
        "name": string;
        "position"?: string;
        "rel"?: string;
        "step"?: string;
        "type": string;
        "units"?: string;
        "value"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapLayer {
        "_opacity"?: number;
        "checked"?: boolean;
        /**
          * @default false
         */
        "hidden": boolean;
        "media"?: string;
        /**
          * @default 1
         */
        "opacity"?: number;
        "src"?: string;
        /**
          * Wait for all map-extent and map-feature elements to be ready. Returns a promise that resolves when all are settled.
         */
        "whenElemsReady": () => Promise<PromiseSettledResult<unknown>[]>;
        "whenReady": () => Promise<void>;
    }
    interface MapLink {
        "disabled"?: boolean;
        "href"?: string;
        "hreflang"?: string;
        "media"?: string;
        "projection"?: string;
        "rel"?: string;
        "tms"?: boolean;
        "tref"?: string;
        "type"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapMeta {
        "content"?: string;
        "name"?: string;
    }
    interface MapProperties {
    }
    interface MapSelect {
        "name"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapSpan {
    }
    interface MapStyle {
        "media"?: string;
    }
    interface MapTile {
        "col"?: number;
        "row"?: number;
        "src"?: string;
        "zoom"?: number;
        "zoomTo": () => Promise<void>;
    }
}
declare global {
    interface HTMLGcdsMapElement extends Components.GcdsMap, HTMLStencilElement {
    }
    var HTMLGcdsMapElement: {
        prototype: HTMLGcdsMapElement;
        new (): HTMLGcdsMapElement;
    };
    interface HTMLMapAElement extends Components.MapA, HTMLStencilElement {
    }
    var HTMLMapAElement: {
        prototype: HTMLMapAElement;
        new (): HTMLMapAElement;
    };
    interface HTMLMapCaptionElement extends Components.MapCaption, HTMLStencilElement {
    }
    var HTMLMapCaptionElement: {
        prototype: HTMLMapCaptionElement;
        new (): HTMLMapCaptionElement;
    };
    interface HTMLMapExtentElement extends Components.MapExtent, HTMLStencilElement {
    }
    var HTMLMapExtentElement: {
        prototype: HTMLMapExtentElement;
        new (): HTMLMapExtentElement;
    };
    interface HTMLMapFeatureElement extends Components.MapFeature, HTMLStencilElement {
    }
    var HTMLMapFeatureElement: {
        prototype: HTMLMapFeatureElement;
        new (): HTMLMapFeatureElement;
    };
    interface HTMLMapFeaturecaptionElement extends Components.MapFeaturecaption, HTMLStencilElement {
    }
    var HTMLMapFeaturecaptionElement: {
        prototype: HTMLMapFeaturecaptionElement;
        new (): HTMLMapFeaturecaptionElement;
    };
    interface HTMLMapGeometryElement extends Components.MapGeometry, HTMLStencilElement {
    }
    var HTMLMapGeometryElement: {
        prototype: HTMLMapGeometryElement;
        new (): HTMLMapGeometryElement;
    };
    interface HTMLMapInputElement extends Components.MapInput, HTMLStencilElement {
    }
    var HTMLMapInputElement: {
        prototype: HTMLMapInputElement;
        new (): HTMLMapInputElement;
    };
    interface HTMLMapLayerElement extends Components.MapLayer, HTMLStencilElement {
    }
    var HTMLMapLayerElement: {
        prototype: HTMLMapLayerElement;
        new (): HTMLMapLayerElement;
    };
    interface HTMLMapLinkElement extends Components.MapLink, HTMLStencilElement {
    }
    var HTMLMapLinkElement: {
        prototype: HTMLMapLinkElement;
        new (): HTMLMapLinkElement;
    };
    interface HTMLMapMetaElement extends Components.MapMeta, HTMLStencilElement {
    }
    var HTMLMapMetaElement: {
        prototype: HTMLMapMetaElement;
        new (): HTMLMapMetaElement;
    };
    interface HTMLMapPropertiesElement extends Components.MapProperties, HTMLStencilElement {
    }
    var HTMLMapPropertiesElement: {
        prototype: HTMLMapPropertiesElement;
        new (): HTMLMapPropertiesElement;
    };
    interface HTMLMapSelectElement extends Components.MapSelect, HTMLStencilElement {
    }
    var HTMLMapSelectElement: {
        prototype: HTMLMapSelectElement;
        new (): HTMLMapSelectElement;
    };
    interface HTMLMapSpanElement extends Components.MapSpan, HTMLStencilElement {
    }
    var HTMLMapSpanElement: {
        prototype: HTMLMapSpanElement;
        new (): HTMLMapSpanElement;
    };
    interface HTMLMapStyleElement extends Components.MapStyle, HTMLStencilElement {
    }
    var HTMLMapStyleElement: {
        prototype: HTMLMapStyleElement;
        new (): HTMLMapStyleElement;
    };
    interface HTMLMapTileElement extends Components.MapTile, HTMLStencilElement {
    }
    var HTMLMapTileElement: {
        prototype: HTMLMapTileElement;
        new (): HTMLMapTileElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-map": HTMLGcdsMapElement;
        "map-a": HTMLMapAElement;
        "map-caption": HTMLMapCaptionElement;
        "map-extent": HTMLMapExtentElement;
        "map-feature": HTMLMapFeatureElement;
        "map-featurecaption": HTMLMapFeaturecaptionElement;
        "map-geometry": HTMLMapGeometryElement;
        "map-input": HTMLMapInputElement;
        "map-layer": HTMLMapLayerElement;
        "map-link": HTMLMapLinkElement;
        "map-meta": HTMLMapMetaElement;
        "map-properties": HTMLMapPropertiesElement;
        "map-select": HTMLMapSelectElement;
        "map-span": HTMLMapSpanElement;
        "map-style": HTMLMapStyleElement;
        "map-tile": HTMLMapTileElement;
    }
}
declare namespace LocalJSX {
    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * @default false
         */
        "controls"?: boolean;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * @default false
         */
        "static"?: boolean;
        /**
          * @default 0
         */
        "zoom"?: number;
    }
    interface MapA {
        "href"?: string;
        "inplace"?: boolean;
        "target"?: string;
        "type"?: string;
    }
    interface MapCaption {
    }
    interface MapExtent {
        "_label"?: string;
        "_opacity"?: number;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "hidden"?: boolean;
        /**
          * @default 1
         */
        "opacity"?: number;
        "units": string;
    }
    interface MapFeature {
        "max"?: number;
        "min"?: number;
        "zoom"?: number;
    }
    interface MapFeaturecaption {
    }
    interface MapGeometry {
        "cs"?: string;
    }
    interface MapInput {
        "axis"?: string;
        "max"?: string;
        "min"?: string;
        "name": string;
        "position"?: string;
        "rel"?: string;
        "step"?: string;
        "type": string;
        "units"?: string;
        "value"?: string;
    }
    interface MapLayer {
        "_opacity"?: number;
        "checked"?: boolean;
        /**
          * @default false
         */
        "hidden"?: boolean;
        "media"?: string;
        /**
          * @default 1
         */
        "opacity"?: number;
        "src"?: string;
    }
    interface MapLink {
        "disabled"?: boolean;
        "href"?: string;
        "hreflang"?: string;
        "media"?: string;
        "projection"?: string;
        "rel"?: string;
        "tms"?: boolean;
        "tref"?: string;
        "type"?: string;
    }
    interface MapMeta {
        "content"?: string;
        "name"?: string;
    }
    interface MapProperties {
    }
    interface MapSelect {
        "name"?: string;
    }
    interface MapSpan {
    }
    interface MapStyle {
        "media"?: string;
    }
    interface MapTile {
        "col"?: number;
        "row"?: number;
        "src"?: string;
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "gcds-map": GcdsMap;
        "map-a": MapA;
        "map-caption": MapCaption;
        "map-extent": MapExtent;
        "map-feature": MapFeature;
        "map-featurecaption": MapFeaturecaption;
        "map-geometry": MapGeometry;
        "map-input": MapInput;
        "map-layer": MapLayer;
        "map-link": MapLink;
        "map-meta": MapMeta;
        "map-properties": MapProperties;
        "map-select": MapSelect;
        "map-span": MapSpan;
        "map-style": MapStyle;
        "map-tile": MapTile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcds-map": LocalJSX.GcdsMap & JSXBase.HTMLAttributes<HTMLGcdsMapElement>;
            "map-a": LocalJSX.MapA & JSXBase.HTMLAttributes<HTMLMapAElement>;
            "map-caption": LocalJSX.MapCaption & JSXBase.HTMLAttributes<HTMLMapCaptionElement>;
            "map-extent": LocalJSX.MapExtent & JSXBase.HTMLAttributes<HTMLMapExtentElement>;
            "map-feature": LocalJSX.MapFeature & JSXBase.HTMLAttributes<HTMLMapFeatureElement>;
            "map-featurecaption": LocalJSX.MapFeaturecaption & JSXBase.HTMLAttributes<HTMLMapFeaturecaptionElement>;
            "map-geometry": LocalJSX.MapGeometry & JSXBase.HTMLAttributes<HTMLMapGeometryElement>;
            "map-input": LocalJSX.MapInput & JSXBase.HTMLAttributes<HTMLMapInputElement>;
            "map-layer": LocalJSX.MapLayer & JSXBase.HTMLAttributes<HTMLMapLayerElement>;
            "map-link": LocalJSX.MapLink & JSXBase.HTMLAttributes<HTMLMapLinkElement>;
            "map-meta": LocalJSX.MapMeta & JSXBase.HTMLAttributes<HTMLMapMetaElement>;
            "map-properties": LocalJSX.MapProperties & JSXBase.HTMLAttributes<HTMLMapPropertiesElement>;
            "map-select": LocalJSX.MapSelect & JSXBase.HTMLAttributes<HTMLMapSelectElement>;
            "map-span": LocalJSX.MapSpan & JSXBase.HTMLAttributes<HTMLMapSpanElement>;
            "map-style": LocalJSX.MapStyle & JSXBase.HTMLAttributes<HTMLMapStyleElement>;
            "map-tile": LocalJSX.MapTile & JSXBase.HTMLAttributes<HTMLMapTileElement>;
        }
    }
}
