/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * Navigate back in map history
         */
        "back": () => Promise<void>;
        /**
          * @default false
         */
        "controls": boolean;
        /**
          * Allows user to move forward in history
         */
        "forward": () => Promise<void>;
        "height"?: string;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * Allows the user to reload/reset the map's location to its initial location and reset the history to the initial state
         */
        "reload": () => Promise<void>;
        /**
          * @default false
         */
        "static"?: boolean;
        /**
          * Toggle debug overlay on the map
         */
        "toggleDebug": () => Promise<void>;
        /**
          * Open the map source in a new window
         */
        "viewSource": () => Promise<void>;
        /**
          * Promise-based method to wait until all layers are ready Returns a promise that resolves when all child layers are fully initialized
         */
        "whenLayersReady": () => Promise<PromiseSettledResult<void>[]>;
        /**
          * Promise-based method to wait until map is ready Returns a promise that resolves when the map is fully initialized
         */
        "whenReady": () => Promise<void>;
        "width"?: string;
        /**
          * @default 0
         */
        "zoom"?: number;
        /**
          * Zoom the map to a specific location and zoom level
          * @param lat - Latitude coordinate
          * @param lon - Longitude coordinate
          * @param zoom - Zoom level (optional, defaults to current zoom)
         */
        "zoomTo": (lat: number, lon: number, zoom?: number) => Promise<void>;
    }
    interface MapLayer {
        "checked"?: boolean;
        "getOuterHTML": () => Promise<string>;
        "label"?: string;
        "media"?: string;
        "opacity"?: number;
        "src"?: string;
        "whenReady": () => Promise<void>;
        "zoomTo": () => Promise<void>;
    }
}
declare global {
    interface HTMLGcdsMapElement extends Components.GcdsMap, HTMLStencilElement {
    }
    var HTMLGcdsMapElement: {
        prototype: HTMLGcdsMapElement;
        new (): HTMLGcdsMapElement;
    };
    interface HTMLMapLayerElement extends Components.MapLayer, HTMLStencilElement {
    }
    var HTMLMapLayerElement: {
        prototype: HTMLMapLayerElement;
        new (): HTMLMapLayerElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-map": HTMLGcdsMapElement;
        "map-layer": HTMLMapLayerElement;
    }
}
declare namespace LocalJSX {
    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * @default false
         */
        "controls"?: boolean;
        "height"?: string;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * @default false
         */
        "static"?: boolean;
        "width"?: string;
        /**
          * @default 0
         */
        "zoom"?: number;
    }
    interface MapLayer {
        "checked"?: boolean;
        "label"?: string;
        "media"?: string;
        "opacity"?: number;
        "src"?: string;
    }
    interface IntrinsicElements {
        "gcds-map": GcdsMap;
        "map-layer": MapLayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcds-map": LocalJSX.GcdsMap & JSXBase.HTMLAttributes<HTMLGcdsMapElement>;
            "map-layer": LocalJSX.MapLayer & JSXBase.HTMLAttributes<HTMLMapLayerElement>;
        }
    }
}
